AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This is a sample serverless application.
Globals:
  Function:
    MemorySize: 128
    Runtime: nodejs14.x
    Timeout: 5
Resources:
  logger:
    Type: AWS::Serverless::Function
    Properties:
      Handler: logger.handler
      Timeout: 3
      Events:
        GetLogs:
          Type: Api
          Properties:
            Path: /logs
            Method: get
        FileUpload:
          Type: S3
          Properties:
            Bucket:
              Ref: S3Bucket
            Events: s3:ObjectCreated:*
      CodeUri: s3://sam-learning/1c8e9ab0e9898168e9b08b4c41a9d419
  S3Bucket:
    Type: AWS::S3::Bucket
  sum:
    Type: AWS::Serverless::Function
    Properties:
      Handler: sum.handler
      Events:
        PostSum:
          Type: Api
          Properties:
            Path: /sum
            Method: post
      CodeUri: s3://sam-learning/1c8e9ab0e9898168e9b08b4c41a9d419
